### ISSUE TITLE
Add negative tests

### ISSUE THREAD

**Issue by harunsmrkovic** [grzim/repository-search#1]
Hey there 👋 

Can we add negative tests here, to make sure wrong callback function is not executed at this moment?

https://github.com/grzim/repository-search/blob/1e7de1925a7afd6df72ca0bf63122c9340392418/src/domains/repository-search-ui/components/Pagination/test/pagination.test.tsx#L54

**Comment by grzim** [comment]
Good idea 👍 negative test added

**Comment by grzim** [comment]
Hello:)
Good idea 👍 tests updated
https://github.com/grzim/repository-search/commit/59301f844d3cafbd96f270cbc756d1c8cde04de0

**Comment by grzim** [comment]
Hello:)
Good idea 👍 tests updated
https://github.com/grzim/repository-search/commit/823a46046049f1344e8b9a6dd3ac2c1c9098778d
